FROM magic/base

ADD ./server /srv
RUN git clone https://github.com/jaeh/jaeh.at.git /srv/hosts/jaeh.at
RUN git clone https://github.com/jaeh/bwb.is.git /srv/hosts/bwb.is
RUN cd /srv; npm install
RUN cd /srv/hosts/jaeh.at; git pull; npm install
RUN cd /srv/hosts/bwb.is; git pull; npm install
EXPOSE  80
CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "node,js,jade,styl" app.js
