FROM magic/base

CMD cd ./server; npm install

CMD npm install -g browserify
CMD cd ./server/hosts/jaeh.at/public/js; browserify ./bundle/index.js > ./main.js
CMD cd ./server/hosts/staging.oliverjiszda.com/public/js; browserify ./bundle/index.js > ./main.js

ADD ./server /srv

EXPOSE |xport|
CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "node,js,jade,styl" app.js
