FROM jascha/express-magic

RUN cd /srv; \
    npm install \
    /srv/.magic-lib/node_modules/express-magic \
    /srv/.magic-lib/node_modules/magic-cache

ADD ./ /srv/hosts

RUN \
  cd /srv/hosts/jaeh.at/public/js; \
  browserify bundle/index.js > main.js && \
  cd /srv/hosts/staging.oliverjiszda.com/public/js; \
  browserify bundle/index.js > main.js && \
  cd /srv/hosts/staging.minotme.com/public/js; \
  browserify bundle/index.js > main.js
  


RUN cd /srv; node --harmony /srv/node_modules/magic-cache/cache.js

EXPOSE |xport|
CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "node,js,jade,styl" app.js
