FROM jascha/magic-base

ADD ./ /srv/hosts

RUN cd /srv/hosts; ./babelify.sh

EXPOSE |xport|

RUN cd /srv; babel src/ --out-file app.js --source-maps

CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "js,jade,styl" \
    --exec babel-node --experimental --ignore='node_modules' -- app.js
