FROM jascha/express-magic

ADD ./ /srv/hosts

RUN \
  cd /srv/hosts/jaeh.at/public/js; \
  browserify bundle/index.js > main.js && \
  cd /srv/hosts/staging.oliverjiszda.com/public/js; \
  browserify bundle/index.js > main.js

EXPOSE |xport|
CMD cd /srv; NODE_ENV=|env| supervisor --harmony --extensions "node,js,jade,styl" app.js
